version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=yourpassword
      POSTGRES_DB=safegate
    networks:
      - safegate-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
       - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/safegate
    networks:
        - safegate-network

  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - safegate-network

volumes:
  postgres_data:

networks:
  safegate-network:
    driver: bridge

  